### ISSUE TITLE
GridInformation.cs error : The name 'HashCode' does not exist in the current context

### ISSUE THREAD

**Issue by luojingzhao** [Unity-Technologies/2d-extras#350]
'HashCode' does not exist
```
internal struct GridInformationKey : IEquatable<GridInformationKey>
{
    public Vector3Int position;
    public String name;

    public bool Equals(GridInformationKey key)
    {
        return position == key.position && name == key.name;
    }

    public override int GetHashCode()
    {
        return HashCode.Combine(position.GetHashCode(), name.GetHashCode());
    }
}
```

**Comment by luojingzhao** [comment]
tag: 2020.3 last version

**Comment by luojingzhao** [comment]
Unity Version: 2020.3.21f,    Api Level: .NET 4.X

**Comment by ChuanXin-Unity** [comment]
Will fix, thanks!

**Comment by ChuanXin-Unity** [comment]
Sorry about this issue, we have updated the branch with a fix!

**Comment by Affan07** [comment]
![image](https://user-images.githubusercontent.com/6506010/197322443-da77a236-2281-4408-bb04-aa83a3533078.png)

Sorry, but the issue still persists with an additional error.

**Comment by ChuanXin-Unity** [comment]
Hi, which version of Unity are you using? The master branch of this repo is
meant for 2021.1 and above. If you are using 2020.3,  could you try the
2020.3 branch of this repo?
